/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'CoffeIcon';
  //static const _kFontPkg = null;

  static const _bFontFam = 'BurgerIcon';
  static const _cFontFam = 'IceCreamIcon';
  static const _dFontFam = 'MinusIcon';
  static const _eFontFam = 'PlusIcon';

  static const IconData coffeIcon = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData burgerIcon = IconData(0xe800, fontFamily: _bFontFam);
  static const IconData iceCreamIcon = IconData(0xe800, fontFamily: _cFontFam);
  static const IconData minuIcon = IconData(0xe800, fontFamily: _dFontFam);
  static const IconData plusIcon = IconData(0xe800, fontFamily: _eFontFam);

}
